import React from "react";
import { Box, Container, Typography, Divider, Link } from "@mui/material";

export default function PrivacyPolicy() {
  return (
    <Container maxWidth="md" sx={{ py: 6 }}>
      {/* Title & Last Updated */}
      <Typography variant="h3" align="center" sx={{ mb: 1 }}>
        Privacy Policy
      </Typography>
      <Typography variant="subtitle1" align="center" sx={{ mb: 4 }}>
        Last updated: March 12, 2025
      </Typography>
      <Divider sx={{ mb: 4 }} />

      {/* Intro */}
      <Typography variant="body1" paragraph>
        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </Typography>
      <Typography variant="body1" paragraph>
        We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
      </Typography>

      {/* Interpretation and Definitions */}
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Interpretation and Definitions
      </Typography>
      <Typography variant="h6" sx={{ mb: 1 }}>
        Interpretation
      </Typography>
      <Typography variant="body1" paragraph>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </Typography>
      <Typography variant="h6" sx={{ mt: 2, mb: 1 }}>
        Definitions
      </Typography>
      <Typography variant="body1" paragraph>
        For the purposes of this Privacy Policy:
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to CrossChain LABS SRL.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Cookies</strong> are small files placed on Your computer, mobile device, or any other device by a website, containing details of Your browsing history on that website among its many uses.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Country</strong> refers to: Bucharest, Romania.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Device</strong> means any device that can access the Service such as a computer, cellphone, or digital tablet.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Service</strong> refers to the Website.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company to facilitate the Service, provide the Service on behalf of the Company, or assist in analyzing how the Service is used.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Website</strong> refers to My Site, accessible from <Link href="https://www.auditron.io/" target="_blank" rel="noopener">https://www.auditron.io/</Link>
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>You</strong> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
      </Typography>

      {/* Collecting and Using Your Personal Data */}
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Collecting and Using Your Personal Data
      </Typography>
      <Typography variant="h6" sx={{ mb: 1 }}>
        Types of Data Collected
      </Typography>
      <Typography variant="subtitle1" sx={{ mb: 1 }}>
        Personal Data
      </Typography>
      <Typography variant="body1" paragraph>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include your email address, first and last name, and usage data.
      </Typography>
      <Typography variant="subtitle1" sx={{ mt: 2, mb: 1 }}>
        Usage Data
      </Typography>
      <Typography variant="body1" paragraph>
        Usage Data is collected automatically when using the Service. It may include information such as your device's IP address, browser type and version, the pages You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
      </Typography>
      <Typography variant="body1" paragraph>
        When accessing the Service via a mobile device, we may automatically collect information such as the type of mobile device, its unique ID, operating system, and browser type.
      </Typography>
      <Typography variant="h6" sx={{ mt: 2, mb: 1 }}>
        Tracking Technologies and Cookies
      </Typography>
      <Typography variant="body1" paragraph>
        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. These may include:
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Cookies or Browser Cookies:</strong> A small file placed on Your Device. You can instruct Your browser to refuse all Cookies or indicate when a Cookie is being sent, but some parts of our Service may not function without them.
      </Typography>
      <Typography variant="body1" paragraph>
        <strong>Web Beacons:</strong> Small electronic files used to count users who have visited pages or opened emails, among other related website statistics.
      </Typography>
      <Typography variant="body1" paragraph>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your device when offline, while Session Cookies are deleted when the browser is closed.
      </Typography>
      <Typography variant="body1" paragraph>
        We use both types of cookies for purposes such as essential authentication, remembering choices, and tracking acceptance of our cookies policy.
      </Typography>

      {/* Use of Your Personal Data */}
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Use of Your Personal Data
      </Typography>
      <Typography variant="body1" paragraph>
        The Company may use Personal Data to:
      </Typography>
      <Typography variant="body1" paragraph>
        • Provide and maintain our Service, including monitoring its usage.
      </Typography>
      <Typography variant="body1" paragraph>
        • Manage Your Account and give access to registered users.
      </Typography>
      <Typography variant="body1" paragraph>
        • Execute contracts for products, services, or other agreements made with Us.
      </Typography>
      <Typography variant="body1" paragraph>
        • Contact You via email, phone, SMS, or push notifications for updates, security alerts, or promotional purposes.
      </Typography>
      <Typography variant="body1" paragraph>
        • Manage Your requests and conduct business transfers, such as mergers or asset sales.
      </Typography>
      <Typography variant="body1" paragraph>
        • Analyze data to improve our Service, products, and overall experience.
      </Typography>
      <Typography variant="body1" paragraph>
        We may share Your personal information with service providers, affiliates, business partners, or with Your consent.
      </Typography>

      {/* Retention, Transfer & Deletion */}
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Retention of Your Personal Data
      </Typography>
      <Typography variant="body1" paragraph>
        The Company will retain Your Personal Data only as long as necessary for the purposes described in this Privacy Policy or as required by law.
      </Typography>
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Transfer of Your Personal Data
      </Typography>
      <Typography variant="body1" paragraph>
        Your data may be transferred to and maintained on computers located outside of your jurisdiction. Your submission of information signifies your agreement to this transfer.
      </Typography>
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Delete Your Personal Data
      </Typography>
      <Typography variant="body1" paragraph>
        You have the right to delete or request the deletion of your Personal Data. You may do so by updating your account settings or contacting us.
      </Typography>

      {/* Disclosure and Security */}
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Disclosure of Your Personal Data
      </Typography>
      <Typography variant="body1" paragraph>
        We may disclose Your Personal Data in situations such as business transactions, legal requirements, or to protect our rights and safety.
      </Typography>
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Security of Your Personal Data
      </Typography>
      <Typography variant="body1" paragraph>
        Although we strive to protect Your Personal Data using commercially acceptable means, no method of transmission over the Internet or electronic storage is 100% secure.
      </Typography>

      {/* Children's Privacy, Links, and Changes */}
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Children's Privacy
      </Typography>
      <Typography variant="body1" paragraph>
        Our Service does not address anyone under the age of 13. We do not knowingly collect information from anyone under 13. If you are a parent and know that your child provided us with Personal Data, please contact us.
      </Typography>
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Links to Other Websites
      </Typography>
      <Typography variant="body1" paragraph>
        Our Service may contain links to third-party websites. We have no control over these sites and are not responsible for their content or privacy practices.
      </Typography>
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Changes to this Privacy Policy
      </Typography>
      <Typography variant="body1" paragraph>
        We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
      </Typography>

      {/* Contact */}
      <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
        Contact Us
      </Typography>
      <Typography variant="body1" paragraph>
        If you have any questions about this Privacy Policy, please contact us by visiting:{" "}
        <Link href="https://www.auditron.io/contact" target="_blank" rel="noopener">
          https://www.auditron.io/contact
        </Link>
      </Typography>
    </Container>
  );
}
